### Tensors

In [1]:
a = [1.0,2.0,1.0]

In [2]:
a[0]

1.0

In [5]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [6]:
import torch
a  = torch.ones(3)
a

tensor([1., 1., 1.])

In [7]:
a[1]

tensor(1.)

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [9]:
points = torch.zeros(6) # tensors of size 6 with all rows
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [10]:
points = torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0]) # another way of creating a tensor 
points

tensor([4., 1., 5., 3., 2., 1.])

In [12]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [13]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]]) # tensfor for higher dimensional objects
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
points.shape # find out the shape of the tensor 

torch.Size([3, 2])

In [18]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
points[0,1] # indexing for the tensors

tensor(1.)

In [23]:
 points[0]

tensor([4., 1.])

In [24]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [25]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [26]:
points[1: , 0]

tensor([5., 2.])

In [27]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [28]:
# Named Tensors

In [30]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2126,0.7152,0.0722])

In [33]:
batch_t = torch.randn(2,3,5,5)

In [35]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [37]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
img_gray_weighted.shape, batch_gray_weighted.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [41]:
# Managing a Tensor dtype attribute

double_points = torch.ones(10,2, dtype = torch.double)
short_points = torch.tensor([[1,2], [3,4]], dtype = torch.short)

In [42]:
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [ ]:
# casting
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(torch.short)

### Indexing Storage

In [2]:
import torch
points = torch.tensor([[4.0,1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

/tmp/ipykernel_1417/3247591840.py:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [3]:
points2 = points.reshape(2,3)
points2

tensor([[4., 1., 5.],
        [3., 2., 1.]])

In [4]:
points2.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

### In Place opertations

In [7]:
a = torch.ones(3,2)
a.storage()

 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [8]:
a.zero_()
a.storage()

 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

### Views of another Tensor Storage

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [11]:
second_point.size()

torch.Size([2])

In [12]:
points.stride()

(2, 1)

**This indirection between Tensor and Storage makes some operations inexpen
sive, like transposing a tensor or extracting a subtensor, because they do not lead to
memory reallocations. Instead, they consist of allocating a new Tensor object with a
different value for size, storage offset, or stride.**

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage(), points.storage()

( 4.0
  1.0
  5.0
  3.0
  2.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6],
  4.0
  1.0
  5.0
  3.0
  2.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6])

In [20]:
second_point[1] = 10
points

tensor([[ 4.,  1.],
        [ 5., 10.],
        [ 2.,  1.]])

In [21]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[1] = 10
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [22]:
second_point.storage(), points.storage()

( 5.0
  10.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 2],
  4.0
  1.0
  5.0
  3.0
  2.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6])

### Transposing without copying

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [30]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [32]:
id(points.storage()) == id(points_t.storage) # i do not know as of now why is it giving me false it should actually be true

False

### Transposing in higher dimension

In [3]:
import torch
some_t = torch.ones(3,4,5)
transpose_t = some_t.transpose(0,2)
some_t.shape

torch.Size([3, 4, 5])

In [4]:
transpose_t.shape

torch.Size([5, 4, 3])

**Both tensors somet and transpose t belong to the same storage but with differnt stride and  offset**

### Contiguous tensors

In [5]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [6]:
points.is_contiguous()

True

In [9]:
points_t = points.t()
points_t.shape

torch.Size([2, 3])

In [10]:
points_t.is_contiguous()

False

**When you take the transpose (points.T), PyTorch doesn’t physically rearrange the data. Instead, it creates a view with different strides (instructions for how to step through memory to access elements).
This view is not contiguous because the elements are no longer in sequential memory order—they’re accessed by jumping across strides.**

**Some operations require contiguous tensors. If you try to use points.T directly in such a case, PyTorch may throw an error or force a copy.
You can fix this by calling .contiguous() on the transposed tensor, which creates a new tensor with the same values but stored in contiguous memory**

In [12]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [13]:
points_t.stride()

(1, 2)

In [14]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [20]:
point_t_cont = points_t.contiguous()

In [22]:
point_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [23]:
point_t_cont.stride()

(3, 1)

**Notice that the storage has been reshuffled in order for elements to be laid out row
by-row in the new storage. The stride has been changed to reflect the new layout.**

### Moving tensors to the GP

**when we’ve talked about storage, we’ve meant memory on the
CPU. PyTorch tensors also can be stored on a different kind of processor: a graphics
processing unit (GPU). Every PyTorch tensor can be transferred to (one of) the
GPU(s) in order to perform massively parallel, fast computations. All operations that
will be performed on the tensor will be carried out using GPU-specific routines that
come with PyTorch**

In [24]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [25]:
points_gpu = points.to(device = 'cuda')

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### NumPy interoperability

To get a NumPy array out of our points tensor, we just call

In [27]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

**which will return a NumPy multidimensional array of the right size, shape, and
numerical type. Interestingly, the returned array shares the same underlying buffer
with the tensor storage. This means the numpy method can be effectively executed at
basically no cost, as long as the data sits in CPU RAM. It also means modifying the
NumPy array will lead to a change in the originating tensor. If the tensor is allocated
on the GPU, PyTorch will make a copy of the content of the tensor into a NumPy array
allocated on the CPU.**

Conversely we can obtain a pytorch tensor form a numpy array like this 

In [28]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Serializing Tensors

**Creating a tensor on the fly is all well and good, but if the data inside is valuable, we will
want to save it to a file and load it back at some point. After all, we don’t want to have
to retrain a model from scratch every time we start running our program! PyTorch uses
pickle under the hood to serialize the tensor object, plus dedicated serialization code
for the storage. Here’s how we can save our points tensor to an ourpoints.t file:**

In [31]:
# saving our tensor
torch.save(points,'./data/p1ch3/ourpoints.t')

In [32]:
# loading our tensor back is also easy
points = torch.load('./data/p1ch3/ourpoints.t')
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Serializing to HDF5 with h5py

**you can use the HDF5 format and
library (www.hdfgroup.org/solutions/hdf5). HDF5 is a portable, widely supported
format for representing serialized multidimensional arrays, organized in a nested key
value dictionary. Python supports HDF5 through the h5py library (www.h5py.org),
which accepts and returns data in the form of NumPy arrays.**

In [34]:
import h5py
f = h5py.File('./data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [36]:
f = h5py.File('./data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [37]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [38]:
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Excersices

In [44]:
a = torch.arange(0,9)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
a.stride()

(1,)

In [46]:
a.size()

torch.Size([9])

In [47]:
b = a.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [48]:
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [49]:
b.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [50]:
id(a.storage()) == id(b.storage())

True

In [51]:
d = torch.cos(a)
d

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [54]:
a = torch.arange(0,9)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
a = a.to(dtype = torch.float)
a.dtype

torch.float32

In [61]:
torch.cos_(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [62]:
a

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])